### PR TITLE
add link for Alabama

### PR DESCRIPTION
**Pull request by micahcochran**

### CODE REVIEW

**Comment by karussell** [comment]
The link seems to be dead?

**Comment by micahcochran** [comment]
It is working for me.  :man_shrugging: 

image

**Comment by karussell** [comment]
This site seems to be down from all German computers I tried but I can confirm that it works from elsewhere. (you can test it here https://tools.pingdom.com)

If you are associated with them - maybe you can have a check and ask them to allow German IPs :) ? Will merge nevertheless.

**Comment by karussell** [comment]
And thanks for the new source!

**Comment by micahcochran** [comment]
It looks like accessing this website from several countries is a problem. 
 (see https://www.uptrends.com/tools/uptime)

**Pull request merged**
